DROP TABLE SEC_USER CASCADE CONSTRAINT;
/*사용자 공통 테이블 - 사용자 추가 정보나 관리자 추가 정보는 USER_ID를 FK로 해서 테이블을 만든다.*/
--Orcale에서 USER는 키워드이므로 사용할 수 없다. (테이블이름으로)
CREATE TABLE SEC_USER(
	USER_ID VARCHAR2(20) PRIMARY KEY,
	USER_PASSWORD VARCHAR2(80) NOT NULL, --암호화를 위해
	USER_NAME VARCHAR2(100) NOT NULL,
	USER_EMAIL VARCHAR2(100) NOT NULL,
	USER_ENABLE NUMBER(1) DEFAULT 1 NOT NULL --1 : 인증가,   0 : 인증불가
);
DROP TABLE AUTHORITIES;
/*권한 테이블 - ROLE_ADMIN, ROLE_MEMBER*/
CREATE TABLE AUTHORITIES(
	USER_ID VARCHAR2(20),
	AUTHORITY VARCHAR2(20) NOT NULL,
	CONSTRAINT AUTHORITIES_PK PRIMARY KEY(USER_ID, AUTHORITY),
	CONSTRAINT AUTHORITIES_SECMEMBER_FK FOREIGN KEY(USER_ID) REFERENCES SEC_USER(USER_ID)
);

select
INSERT INTO SEC_USER VALUES('admin', '94a452f9b88069ebbf10a5ca70fb53937497aa65132db24bf4af751db26dbd880313a2f15b31d020', '관리자', 'admin@a.com', 1); --pwd : 1111

INSERT INTO AUTHORITIES VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES VALUES ('admin', 'ROLE_MEMBER');

INSERT INTO AUTHORITIES VALUES ('id-1', 'ROLE_ADMIN');


select * from AUTHORITIES where user_id = 'id-1'






















