DROP TABLE IMAGES;
CREATE TABLE IMAGES(
	IMAGE_NO NUMBER PRIMARY KEY,
	IMAGE_SAVE_NAME CHAR(36) NOT NULL, --UUID로 생성된 문자열 (36글자)
	IMAGE_ORIGINAL_NAME VARCHAR2(100) NOT NULL,
	IMAGE_DESCRIPTION VARCHAR2(500) NOT NULL
);

DROP SEQUENCE IMAGES_NO_SEQ;
CREATE SEQUENCE IMAGES_NO_SEQ NOCACHE;

